### ISSUE TITLE
Mockup de la GUI

### ISSUE THREAD

**Issue by Carlossh2200** [Carlossh2200/Algorithm-Analysis-Project#1]
Hacer el mockup de la interfaz de usuario tomando en cuenta lo acordado.

**Comment by FabioP15** [comment]
![Image](https://github.com/Carlossh2200/Algorithm-Analysis-Project/assets/108777166/e6897a52-6bf4-4f7f-8020-ba99f7f28ed8)

Primera version del mockup, esperando review

**Comment by Carlossh2200** [comment]
Qué tal algo más espaciado? tipo así 



![Image](https://github.com/Carlossh2200/Algorithm-Analysis-Project/assets/123311957/9f013ffa-7a59-4be4-91ae-b0f4db834be9)
