### ISSUE TITLE
Definir cual biblioteca se usará para la implentacion de la GUI

### ISSUE THREAD

**Issue by Carlossh2200** [Carlossh2200/Algorithm-Analysis-Project#12]
De acuerdo al problema, los tiempos de entrega y la capacidad del desarrollador, tener definida cuál será la biblioteca a usar para conectar el back-end y el front-end

**Comment by FabioP15** [comment]
Como se comenta en la clase el pasado miercoles, se decidio por la libreria TKinter. Esto debido a la experiencia que ya tienen algunos compañeros con esta herramienta
